export const environmentKey = {
    MOBILE_PHONE_NUMBER: 'VITE_MOBILE_PHONE_NUMBER',
    MOBILE_PHONE_NUMBER_VISUAL: 'VITE_MOBILE_PHONE_NUMBER_VISUAL',
    EMAIL: 'VITE_EMAIL',
    LINKEDIN: 'VITE_LINKEDIN',
}